# Generated by Django 6.0 on 2025-12-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_add_is_visible_to_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='batch',
        ),
        migrations.AlterField(
            model_name='batch',
            name='date',
            field=models.DateField(help_text='Tanggal mulai batch tryout'),
        ),
    ]
