# Generated by Django 6.0 on 2025-12-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch yang menggunakan soal ini (opsional untuk backward compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='quiz.batch'),
        ),
    ]
