# Generated by Django 6.0 on 2025-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_soal_soal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='ID batch (mis. batch-1)', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Judul batch (mis. TryOut UTBK Batch 1)', max_length=200)),
                ('date', models.DateField(help_text='Tanggal batch tryout')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('locked', 'Terkunci')], default='locked', help_text='Status batch', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Deskripsi batch (opsional)', null=True)),
                ('deadline', models.DateField(help_text='Tanggal terakhir bisa mengakses batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
