# Generated by Django 6.0 on 2025-12-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_soal_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Tampilkan batch di dashboard tryout user'),
        ),
    ]
