# Generated by Django 6.0 on 2025-12-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_soal_batch_alter_batch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch tryout yang memiliki soal ini', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='quiz.batch'),
        ),
    ]
